services:
  caddy:
    image: caddy:2-alpine
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  server:
    image: ghcr.io/bananatransfer/bananatransfer:latest
    restart: always
volumes:
  caddy_data: