name: "AWS deploy"
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key for the account the deployment must take place in'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key for AWS_ACCESS_KEY_ID'
    required: true
  ENVIRONMENT_NAME:
    description: 'Name used in every deployment artifact (server name, s3 bucket, ...)'
    required: true
  SSH_PUB_KEY:
    description: 'SSH key to be deployed on the server to be able to connect on it'
    required: true
  SSH_PRIV_KEY:
    description: 'SSH private key associated to the SSH_PUB_KEY'
    required: true
  INTERNAL_HOSTNAME:
    description: 'DNS record to be created on a domain managed by AWS route 53. Will be associated to the server IP'
    required: true
  EXTERNAL_HOSTNAME:
    description: 'DNS record that will be used by user to access the server. Either a CNAME to the INTERNAL_HOSTNAME or the INTERNAL_HOSTNAME itself'
    required: true
  DOMAIN:
    description: 'Domain name used and managed by the bananatransfer server'
    required: true
  DOCKER_REPO_USER:
    description: 'User used by the server to retrieve the docker image from GitHub artifact repository'
    required: true
  DOCKER_REPO_TOKEN:
    description: 'Token associated to DOCKER_REPO_USER'
    required: true
  DB_USER:
    description: 'User of the postgresql database'
    required: true
  DB_PASS:
    description: 'Password of the postgresql user'
    required: true
  JWT_SECRET:
    description: 'AES 256bit key used to sign JWT token'
    required: true
  DOCKER_IMAGE_TAG:
    description: 'TAG to select which bananatransfer docker image to use'
    required: true
    default: latest
runs:
  using: "composite"
  steps:
    - name: Configure the AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Initialise terraform
      run: terraform init -backend-config="key=${{ inputs.ENVIRONMENT_NAME }}"
      working-directory: infra/terraform
      shell: bash
    - name: Create the AWS infrastructure
      run: |
        terraform apply -auto-approve \
          -var="ssh_pub_key=${{ inputs.SSH_PUB_KEY }}" \
          -var="environment_name=${{ inputs.ENVIRONMENT_NAME }}" \
          -var="hostname=${{ inputs.INTERNAL_HOSTNAME }}"
      working-directory: infra/terraform
      shell: bash
    - name: Install python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Ansible
      run: pip install -r requirements.txt
      working-directory: infra/ansible
      shell: bash
    - name: Add docker collection for ansible
      run: ansible-galaxy collection install community.docker
      shell: bash
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.SSH_PRIV_KEY }}
    - name: Fill the missing filter tag in the ansible dynamic inventory
      run: |
        cp partial_inventory_aws_ec2.yml inventory_aws_ec2.yml
        echo "  tag:environment: ${{ inputs.ENVIRONMENT_NAME }}" >> inventory_aws_ec2.yml
      working-directory: infra/ansible
      shell: bash
    - name: Deploy on EC2
      run: |
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory_aws_ec2.yml playbook.yml \
          -e "github_username=${{ inputs.DOCKER_REPO_USER }}" \
          -e "github_token=${{ inputs.DOCKER_REPO_TOKEN }}" \
          -e "db_user=${{ inputs.DB_USER }}" \
          -e "db_pass=${{ inputs.DB_PASS }}" \
          -e "s3_bucket=bananatransfer-${{ inputs.ENVIRONMENT_NAME }}-s3-bucket" \
          -e "internal_hostname=${{ inputs.INTERNAL_HOSTNAME }}" \
          -e "external_hostname=${{ inputs.EXTERNAL_HOSTNAME }}" \
          -e "domain=${{ inputs.DOMAIN }}" \
          -e "jwt_secret=${{ inputs.JWT_SECRET }}" \
          -e "docker_image_tag=${{ inputs.DOCKER_IMAGE_TAG }}" \
          -u admin
      working-directory: infra/ansible
      shell: bash
