name: Code quality checks
description: Verify the code quality by running test, eslint and building the project
runs:
  using: "composite"
  steps:
    - name: Install Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Audit dependencies
      # the check only fails if there are vulnerabilities with the severity moderate or higher
      run: npm audit --audit-level=moderate 
      shell: bash
    - name: Run the linter # test code quality
      run: npm run lint
      shell: bash
    - name: Build # test for build error (like typechecking)
      run: npm run build
      shell: bash
    - name: Run tests
      run: npm test
      shell: bash
    - name: Run tests for public js
      run: npm run test:public
      shell: bash
    - name: Build the js files
      run: npm run build:public
      shell: bash
