name: Build and push docker image
inputs:
  tag:
    required: true
runs:
  using: "composite"
  steps:
    - name: Define Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: type=raw,value=${{ inputs.image_tag }}
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}