@startuml
title Architecture Server

rectangle "BananaTransfer Server" as srv {
    rectangle "Node.js" as node {
        rectangle "Frontend \n(pug templates)" as frontend
        rectangle "Backend /api \n(NestJS)" as backend {
            rectangle "auth module \n(user authentication)" as auth {
              rectangle "jwt core module \n(jwt creation and validation)" as jwt
            }
            rectangle "database module \n(access to db)" as db_mod
            rectangle "transfer module \n(create and access transfers)" as transfer
            '{
              'rectangle "transfer controller \n(authenticated endpoints to \ncreate and access transfer)" as transfercontroller
              'rectangle "remote controller \n(transfer api for other servers)" as remotecontroller
            '}
            rectangle "user module \n(manage user account / keys)" as usr
        }
    }
    rectangle "Database \nPostgreSQL" as db
    rectangle "Bucket \nS3 / MinIO" as s3
}

db_mod -down-> db: "query/save"
transfer -down-> s3: "fetch/save"
transfer --> db_mod
transfer --> usr
usr --> db_mod
auth --> usr

@enduml