@startuml

enum UserStatus {
    ACTIVE
    DISABLED
    BLOCKED
    DELETED
}

enum TransferStatus {
    CREATED
    PENDING
    RETRIEVED
    DELETED
    EXPIRED
    REFUSED
}

class User {
    id: bigserial
    username: text
    created_at: timestamp
}

class LocalUser {
    status: UserStatus
    last_login: timestamp
    password_hash_salt: text
    private_key_encrypted: text
    private_key_kdf_salt: text 32bits
    public_key: text
    key_created_at: timestamp
}

class RemoteUser {
    domain: text
}

class FileTransfer {
    id: bigserial
    symmetric_key_encrypted: text
    signature_sender: text
    status: TransferStatus
    created_at: timestamp
    filename: varchar
    subject: varchar
    s3_path: text [optional]
}

class TrustedRecipient {
    public_key_hash: text
    created_at: timestamp
}

class Log {
    id: bigserial
    text: text
    created_at: timestamp
}

LocalUser -up-|> User
RemoteUser -up-|> User

User "1" -- "*" FileTransfer: sends >
User "1" -- "*" FileTransfer: receives >

LocalUser "1" -- "*" TrustedRecipient: knows/trusts >
TrustedRecipient "*" -- "1" User: associated to >

User "0..1" -- "*" Log: logs >
FileTransfer "0..1" -- "*" Log: logs >

@enduml