name: Docker Build and Publish
on:
  push:
    branches: ["**"]
    paths-ignore:
      - "documents/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    environment: e2e
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Validate the code quality
        uses: ./.github/actions/code_quality_check
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Define Docker image for integration test
        id: e2e_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=e2e
      - name: Build and push integration test docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.e2e_meta.outputs.tags }}
          labels: ${{ steps.e2e_meta.outputs.labels }}
      - name: Deploy integration test environment A
        uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT_NAME: e2e-A
          SSH_PUB_KEY: ${{ vars.SSH_PUB_KEY }}
          SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
          INTERNAL_HOSTNAME: A.${{ vars.BASE_HOSTNAME }}
          EXTERNAL_HOSTNAME: A.${{ vars.BASE_HOSTNAME }}
          DOCKER_REPO_USER: ${{ secrets.DOCKER_REPO_USER }}
          DOCKER_REPO_TOKEN: ${{ secrets.DOCKER_REPO_TOKEN }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DOMAIN: A.${{ vars.BASE_HOSTNAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOCKER_IMAGE_TAG: e2e
      # NPM + dep installed in the code quality check action
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run e2e
      # Upload playwright test artifacts for review on github servers
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # terraform env configured in the deploy action
      - name: Destroy the integration test environment A
        if: ${{ !cancelled() }} # run even in case of failure, but not if cancelled
        run: | 
          terraform destroy -auto-approve -auto-approve -input=false \
            -var="ssh_pub_key=${{ vars.SSH_PUB_KEY }}" \
            -var="environment_name=e2e-A" \
            -var="hostname=A.${{ vars.BASE_HOSTNAME }}"
        working-directory: infra/terraform
        shell: bash
      - name: Define Docker image tags for latest
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=latest
      - name: Build and push latest docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy_saul:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: saul
      url: bananatransfer.saul.ch
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          SSH_PUB_KEY: ${{ vars.SSH_PUB_KEY }}
          SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
          INTERNAL_HOSTNAME: ${{ vars.INTERNAL_HOSTNAME }}
          EXTERNAL_HOSTNAME: ${{ vars.EXTERNAL_HOSTNAME }}
          DOCKER_REPO_USER: ${{ secrets.DOCKER_REPO_USER }}
          DOCKER_REPO_TOKEN: ${{ secrets.DOCKER_REPO_TOKEN }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DOMAIN: ${{ vars.DOMAIN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
  deploy_ansermoz:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: ansermoz
      url: bananatransfer.ansermoz.dev
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          SSH_PUB_KEY: ${{ vars.SSH_PUB_KEY }}
          SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
          INTERNAL_HOSTNAME: ${{ vars.INTERNAL_HOSTNAME }}
          EXTERNAL_HOSTNAME: ${{ vars.EXTERNAL_HOSTNAME }}
          DOCKER_REPO_USER: ${{ secrets.DOCKER_REPO_USER }}
          DOCKER_REPO_TOKEN: ${{ secrets.DOCKER_REPO_TOKEN }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DOMAIN: ${{ vars.DOMAIN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}