name: Docker Build and Publish
on:
  push:
#on:
#  push:
#    branches: ["main"]
#    paths-ignore:
#      - "documents/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
#      - name: Validate the code quality
#        uses: ./.github/actions/code_quality_check
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Define Docker image tags
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ghcr.io/${{ github.repository }}
#          tags: type=raw,value=latest
#      - name: Build and push latest docker image
#        id: push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
  deploy_saul:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: saul
      url: bananatransfer.saul.ch
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          SSH_PUB_KEY: ${{ vars.SSH_PUB_KEY }}
          SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
          INTERNAL_DOMAIN: ${{ vars.INTERNAL_DOMAIN }}
          EXTERNAL_DOMAIN: ${{ vars.EXTERNAL_DOMAIN }}
          DOCKER_REPO_USER: ${{ secrets.DOCKER_REPO_USER }}
          DOCKER_REPO_TOKEN: ${{ secrets.DOCKER_REPO_TOKEN }}
  deploy_ansermoz:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: ansermoz
      url: bananatransfer.ansermoz.dev
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          SSH_PUB_KEY: ${{ vars.SSH_PUB_KEY }}
          SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
          INTERNAL_DOMAIN: ${{ vars.INTERNAL_DOMAIN }}
          EXTERNAL_DOMAIN: ${{ vars.EXTERNAL_DOMAIN }}
          DOCKER_REPO_USER: ${{ secrets.DOCKER_REPO_USER }}
          DOCKER_REPO_TOKEN: ${{ secrets.DOCKER_REPO_TOKEN }}

